modLoader = "javafml"
loaderVersion = "@loaderVersionRange@"
license = "MIT"

[[mods]]
modId = "mtr"
version = "@version@"
displayName = "Minecraft Transit Railway"
authors = "Jonathan Ho"
description = "A Minecraft mod that adds automated train systems into the game."
logoFile = "icon.png"

[[dependencies.mtr]]
modId = "neoforge"
type = "required"
versionRange = "@neoForgeVersionRange@"
ordering = "NONE"
side = "BOTH"

[[dependencies.mtr]]
modId = "minecraft"
type = "required"
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"
